
FROM debian
ADD docker.list /etc/apt/sources.list.d/
RUN apt-get update && apt-get -y upgrade && apt -y install nginx && apt-get clean && \
    cd /var/www/ && rm -rf ./* && \
    mkdir -p firstclone.com/img && \
    chmod -R 754 /var/www/firstclone.com/ && \
    useradd Kirill && groupadd Tikhomirov && usermod -aG Tikhomirov Kirill && \
    chown -R Kirill:Tikhomirov /var/www/firstclone.com/ && \
    sed -i 's/\/var\/www\/html/\/var\/www\/firstclone.com/g' /etc/nginx/sites-enabled/default && \
    sed -i 's/user www-data/user Kirill/g' /etc/nginx/nginx.conf
ADD index.html /var/www/firstclone.com/
ADD img.jpg /var/www/firstclone.com/img/
CMD ["nginx", "-g", "daemon off;"]
